version: 0.0
os: linux
hooks:
  BeforeInstall:
    - location: installmaven.sh
  AfterInstall:
    - location: build.sh
      timeout: 180
  ApplicationStart:
    - location: test.sh
      timeout: 3600
  ValidateService:
    - location: test.sh
      timeout: 3600
